import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import Navbar from '@/components/Navbar';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
          <Navbar />
          <div className="flex pt-16 min-h-screen">
            <Sidebar />
            <main className="flex-1 ml-16 p-4 overflow-y-auto">
              {children}
            </main>
          </div>
        </body>
      </html>
    );
  }
